### ISSUE TITLE
Asking about merging

### ISSUE THREAD

**Issue by KaranAhlawat** [sollidsnake/emacs#1]
Hi, sorry to bother on this old repo.

I was following the mailing list about this patch, but I'm not sure if it got merged in the end? Or did you face some blockers, or simply lost interest in getting it merged? 

Thanks for your time with this, I had no clue where to start tweaking the code 😄

**Comment by sollidsnake** [comment]
Hi! Unfortunately it wasn't merged. They asked for some changes in that patch, which I worked on, but they were not enough. Back then I was too busy with other stuff and ended up signing a document giving the FSF the rights to the patch, so that they could work on any remaining changes that they deemed necessary. But, AFAIK, there wasn't any work done after that.

I remember that one of the maintainers suggest a different, more flexible approach than what I did in the patch, but I don't think anyone has worked on it yet.

Right now I'm building Emacs from source to apply the patch, which is working just fine. I have a [repo with a Arch Linux's PKGBUILD](https://github.com/sollidsnake/emacs-vertical-center-patch-git) to automate the process, if you're interested.

**Comment by KaranAhlawat** [comment]
Thanks for the reply. First, I appreciate you figuring out the needed code changes, I'd been trying to for a couple days but got lost in xdisp.c

I've also applied the patch to a local checkout and building off of that, works great so far.

On a side note, when using this, the cursor shrinks down to the size of the character it's on. Did you also  run into a similar issue? I'm thinking of making it more VSCode, where the cursor height stays constant, but haven't been able to find a way yet.

**Comment by sollidsnake** [comment]
It's nice to hear it's worked for you :)

The cursor size felt fine for me, so I didn't bother messing with it. I believe it wouldn't be too hard doing it, but I would need to dive in into the Emacs source code again to have an idea of what it would take.

You see, every now and then I get some feedback asking about the status of this patch. Maybe it could help replying to the mailing list, asking the maintainers, to show them that there's interest in this feature.

**Comment by KaranAhlawat** [comment]
I've just been playing around with different properties to see what it takes. Will update if something works out. 

Yeah, it would. I should probably learn how to interact on a mailing list XD

Should I keep this open or close it? I don't think there's any further need to keep it open on my end.

**Comment by sollidsnake** [comment]
If you make any progress please share :)

I had never interacted with a mailing list before submitting this patch. My personal opinion is that this "archaic" process  of Emacs, instead of a regular git repo with issues, delays a little bit its progress by holding back new people from contributing. Hopefully it will get better in the future.

I'm closing this issue, but feel free to get in touch if anything comes up. Have a good day!

**Comment by dgutov** [comment]
It might be useful to link to the bug report here. If you filed one, as opposed to sending an email to emacs-devel.
